name: Build and deploy container app to Azure Web App - demo-pdp-emperia-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://emperiadev.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_446cb9b769fe4407b876bdf9a455a00b }}
          password: ${{ secrets.AzureAppService_ContainerPassword_c3313c3c7def4dc981e0352c8e13d298 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: emperiadev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_446cb9b769fe4407b876bdf9a455a00b }}/appsvc/staticsite:${{ github.sha }}
          file: ./Dockerfile

   deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'demo-pdp-emperia-api-stagging'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'demo-pdp-emperia-api'
            slot-name: 'demo-pdp-emperia-api-stagging'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_6d6d8e81bdb44e3c893016f627b7f98c }}
            images: 'emperiadev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_446cb9b769fe4407b876bdf9a455a00b }}/appsvc/staticsite:${{ github.sha }}'
